chore(CI): add OBS workflows
linuxdeepin/dde-daemon pull request #486
Opened 2023-03-23 08:34 UTC by dengbo11

add OBS workflows

Log:

2023-03-24 02:59 UTC, zsien requested changes
是不是应该把 .obs 加到 reuse 里

2023-03-28 07:40 UTC, zsien approved these changes

2023-03-29 01:50 UTC, tsic404 requested changes

2023-03-29 01:50 UTC, tsic404 commented on .obs/workflows.yml
> +        project: ddeepin:Develop:dde
typo

2023-03-29 05:39 UTC, dengbo11 commented on .obs/workflows.yml
> +        project: ddeepin:Develop:dde
Done

2023-03-29 05:49 UTC, tsic404 approved these changes

2023-03-29 06:02 UTC, merged