chore: modify the startup order of session daemon
linuxdeepin/dde-daemon pull request #543
Opened 2023-08-25 06:54 UTC by chenchongbiao

修改 session-daemon 的启动顺序，添加到dde-session-initialized.target.wants 中

Log: modify the startup order

2023-08-25 06:54 UTC, chenchongbiao commented
@Decodetalkers

2023-08-25 07:34 UTC, dengbo11 approved these changes

2023-08-25 07:40 UTC, Decodetalkers commented on debian/rules
>  	rm debian/dde-daemon/etc/grub.d/35_deepin_gfxmode
这边其实是用了if包起来的。其他条件没问题吗

2023-08-28 05:51 UTC, Decodetalkers commented on Makefile
> +    ln -s $(PREFIX)/lib/systemd/user/org.dde.session.Daemon1.service \
先
```
mkdir -p $(DESTDIR)$(PREFIX)/lib/systemd/user/dde-session-initialized.target.wants/
```
另外注意缩进

2023-08-28 05:59 UTC, justforlxz requested changes

2023-08-28 05:59 UTC, justforlxz commented on misc/systemd/services/org.dde.session.Daemon1.service
> +WantedBy=graphical-session.target
删除，该服务无需安装。

2023-08-28 06:18 UTC, justforlxz approved these changes

2023-08-28 06:23 UTC, Decodetalkers approved these changes

2023-08-28 06:23 UTC, dengbo11 commented
/integrate

2023-08-28 06:25 UTC, merged