fix: when power governer changed, mode not changed
linuxdeepin/dde-daemon pull request #552
Opened 2023-09-13 07:47 UTC by Decodetalkers

Log: this add a fsnotify

2023-09-13 07:55 UTC, dengbo11 commented on system/power1/manager.go
> +		defer watcher.Close()
这一行要放到162行

2023-09-13 08:05 UTC, dengbo11 requested changes

2023-09-13 08:05 UTC, dengbo11 commented on system/power1/manager.go
> +								}
这里可以封装成一个函数

2023-09-13 08:39 UTC, dengbo11 approved these changes

2023-09-13 09:49 UTC, dengbo11 submitted a review, later dismissed

2023-09-13 10:12 UTC, dengbo11 commented on system/power1/manager.go
> +			}
if (err ==nil && modeAndgovData.mode != "") {
    m.setPropMode(modeAndgovData.mode)
    m.setPropCpuGovernor(modeAndgovData.governor)
}

2023-09-13 10:17 UTC, dengbo11 approved these changes

2023-09-14 01:47 UTC, dengbo11 approved these changes

2023-09-14 02:54 UTC, merged

2023-09-14 02:54 UTC, Decodetalkers commented
/integrate

2023-09-14 02:58 UTC, Decodetalkers commented
https://github.com/linuxdeepin/developer-center/issues/5115