feat(power)!: switch backend from lmt to tlp
linuxdeepin/dde-daemon pull request #559
Opened 2023-09-25 03:38 UTC by Decodetalkers

Log:

2023-09-26 01:52 UTC, Decodetalkers commented
@xzl01

2023-09-28 01:49 UTC, dengbo11 requested changes

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_bluetoothadapter.go
> +)
添加空行，下面几处同理

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_powersave.go
> +	// var tlpCfgChanged bool
不需要的变量删掉

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_tlp.go
> +	//"github.com/linuxdeepin/go-lib/dbusutil"
不需要的包删掉

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_tlp.go
> +		logger.Warning(err)
这一行可以移到65行

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_tlp.go
> +	defer f.Close()
这一行移动到156行

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_tlp.go
> +	defer f.Close()
移动到197行

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager.go
> +	changed = m.setPropPowerSavingModeEnabled(enable)
如果这个属性没有change, 是否还需要写呢

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager_powersave.go
> +	ConfigManager "github.com/linuxdeepin/go-dbus-factory/org.desktopspec.ConfigManager"
ConfigManager小写命名

2023-09-28 01:49 UTC, dengbo11 commented on system/power1/manager.go
> +		m.setPowerSavingModeEnabled(false)
这里是否需要加锁，下面两处同理

2023-09-28 06:48 UTC, Decodetalkers commented on system/power1/manager.go
> +		m.setPowerSavingModeEnabled(false)
嗯，我看powersave那边也加锁了，那这边确实要加锁

2023-10-07 01:53 UTC, dengbo11 submitted a review, later dismissed

2023-10-23 03:30 UTC, Decodetalkers commented
那个锁在manager已经锁了一次了，所以如果再锁就会卡住

2023-10-25 02:27 UTC, Decodetalkers commented
需要调研

2024-02-20 01:47 UTC, closed without merging