feat: add audio server switch support
linuxdeepin/dde-daemon pull request #577
Opened 2023-11-02 09:22 UTC by chenchongbiao

add audio server switch support

Issue: https://github.com/linuxdeepin/developer-center/issues/5819
Log: add audio server switch support

2023-11-06 05:45 UTC, chenchongbiao commented
/integrate

2023-11-09 03:25 UTC, chenchongbiao commented
/topic icon

2023-11-10 05:05 UTC, dengbo11 submitted a review, later dismissed

2023-11-10 06:20 UTC, chenchongbiao commented
/integr-topic icon

2023-11-10 10:23 UTC, chenchongbiao commented
/integr-topic icon

2023-11-13 01:48 UTC, dengbo11 requested changes

2023-11-13 01:48 UTC, dengbo11 commented on audio1/audio.go
> +	oldAudioServer := a.CurrentAudioServer
和锁不相关的操作不要放到锁里面，尽量减小锁的粒度

2023-11-13 01:48 UTC, dengbo11 commented on audio1/audio.go
> +	_, e := systemd.UnmaskUnitFiles(0, activeServers, false)
注意变量命名，可以用err

2023-11-13 02:34 UTC, chenchongbiao commented on audio1/audio.go
> +	_, e := systemd.UnmaskUnitFiles(0, activeServers, false)
ok

2023-11-13 06:26 UTC, dengbo11 approved these changes

2023-11-13 06:43 UTC, chenchongbiao commented
/integr-topic icon

2023-11-13 07:14 UTC, chenchongbiao commented
/integr-topic icon

2023-11-13 09:07 UTC, chenchongbiao commented
/integr-topic icon

2023-11-13 09:30 UTC, chenchongbiao commented
/integr-topic icon

2023-11-13 13:42 UTC, chenchongbiao commented
/integr-topic icon

2023-11-14 05:15 UTC, dengbo11 requested changes

2023-11-14 05:15 UTC, dengbo11 commented on audio1/audio.go
> +		deactiveServers = []string{pipewireService, pipewirePulseService, pipewireSocket, pipewirePulseSocket}
有多处用到这个两个变量，可以定义包内的全局变量

2023-11-14 05:28 UTC, chenchongbiao commented
/integr-topic icon

2023-11-14 05:43 UTC, chenchongbiao commented
/integr-topic icon

2023-11-14 10:20 UTC, dengbo11 submitted a review, later dismissed

2023-11-15 02:25 UTC, chenchongbiao commented
/integr-topic icon

2023-11-15 05:04 UTC, dengbo11 approved these changes

2023-11-15 08:18 UTC, merged